### ISSUE TITLE
Error filtering cams

### ISSUE THREAD

**Issue by xalaros** [aitschti/plugin.video.sc19#1]
Kodi 20.1 with addon SC19 v1.2.0 appears all categories "Error filtering cams".

**Comment by xalaros** [comment]
Thanks for quick response. On Windows 10 plays fine but on Android TV (internt working) when opening every category appears "Error filtering cams".

**Comment by xalaros** [comment]
CB20 plays fine both Windows & Android TV ... so maybe on Android TV dns blocking SC19

**Comment by aitschti** [comment]
Thanks for checking this out. As SC19 works on your windows box and on my windows and android box, the issue seems to be on your side. I do not know of any block your android box may have. Feel free to comment, if you find out what is going on. Sorry that I cannot help more than that.

**Comment by aitschti** [comment]
If there is nothing new, I will close this issue in the next couple of days as the problem does not seem to be in the scope of the plugin.

**Comment by xalaros** [comment]
Yes, you can close it. Sorry not answer before but problem is from DNS adblocking.

**Comment by aitschti** [comment]
Thanks for the feedback. If DNS blocking is the problem, maybe another URL would work. Normally, the plugin connects to stripchat.com. If you open the website in your browser, it most likely will redirect and connect to something like countrycode.stripchat.com, where countrycode is your two letter countrycode based off your browser's language. Using the countrcode to connect may help. IPs seem to be identical for the stripchat urls, but it may work. I could add an option in the settings to use another url to connect to stripchat, like nl.stripchat.com.
