### ISSUE TITLE
SC19 Error Filtering Cams

### ISSUE THREAD

**Issue by brimacbt** [aitschti/plugin.video.sc19#4]
For about the last 4 days, SC19 has thrown up an "error filtering cams" message every time I try to open a category in stripchat, i.e., girls...all; or couples...all. The only category that doesn't throw up this message is favorites. This happens for me on three different Sony OLED TVs, an Nvidia Shield, and on a Windows 10 PC, on version 1.5.0 and version 1.4.6. I am running Kodi 21.1 on one Sony and the PC and 20.5 on all the others. I am in Canada if that helps. I love this useful addon and hope somebody can fix this issue. Thanks.

**Comment by aitschti** [comment]
Noticed this myself the other day. Will attend to it, when I get back to my PC. Bug aknowledged. SC must have been changing their api calls...

**Comment by brimacbt** [comment]
Thanks so much!
